function [] = set_default_properties()
%SET_DEFAULT_PROPERTIES Summary of this function goes here
%   Detailed explanation goes here
text = strcat('<?xml version="1.0" encoding="utf-8"?>',...
    '<properties>',...
    '<run_mode description="HPC-option1">0</run_mode>',...
    '<run_single_subject>0</run_single_subject>',...
    '<run_frequency_bin>0</run_frequency_bin>',...
    '<methods>',...
    '<beamfomer name="Beamfomer" run="true"/>',...
    '<bma name="BMA" run="true"/>',...
    '<eloreta name="" run="false"/>',...
    '<enetmm name="" run="false"/>',...
    '<lassomm name="" run="false"/>',...
    '<loreta name="" run="false"/>',...
    '<enetssbl name="" run="false"/>',...
    '<sloreta name="" run="false"/>',...
    '<sttonnica name="" run="false"/>', ...
    '</methods>',...
    '<data_path>D:\NeuroInformatics Lab\BC-VARETA1.0_repo\data</data_path>',...
    '<delta_band end="4" name="delta" run="true" start="0.1"/>',...
    '<theta_band end="7" name="theta" run="true" start="4"/>',...
    '<alpha_band end="14" name="alpha" run="true" start="7"/>',...
    '<beta_band end="31" name="beta" run="true" start="14"/>',...
    '<freq_resol description="Frequency resolution">0.3609</freq_resol>',...
    '<samp_freq description="Sampling frequency">100</samp_freq>',...
    '<max_freq description="Maximum frequency">32</max_freq>',...
    '</properties>');

xmlwrite(strcat('properfties',filesep,'properties.xml'),text);

end

